# Generated by Django 3.0.2 on 2020-01-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('City', models.TextField()),
                ('State', models.TextField()),
                ('Zip', models.TextField()),
                ('Floor', models.TextField()),
                ('IsActive', models.BooleanField(default=True)),
                ('Image', models.ImageField(upload_to='pics')),
                ('CreationDate', models.DateField()),
                ('CreationBy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.TextField()),
                ('Email', models.TextField()),
                ('Name', models.TextField()),
                ('Department', models.TextField()),
                ('Designation', models.TextField()),
                ('UserName', models.TextField()),
                ('Password', models.TextField()),
                ('Image', models.ImageField(upload_to='pics')),
                ('IsActive', models.BooleanField(default=True)),
                ('CreationDate', models.DateField()),
                ('CreationBy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuestName', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('City', models.TextField()),
                ('State', models.TextField()),
                ('Zip', models.TextField()),
                ('Occupation', models.TextField()),
                ('Designation', models.TextField()),
                ('LengthOfStay', models.IntegerField()),
                ('PhoneNo', models.IntegerField()),
                ('IsActive', models.BooleanField(default=True)),
                ('GuestImage', models.ImageField(upload_to='pics')),
                ('CreationDate', models.DateField()),
                ('CreationBy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeId', models.IntegerField()),
                ('EmployeeCode', models.TextField()),
                ('Purpose', models.TextField()),
                ('RoomId', models.IntegerField()),
                ('MeetingDate', models.DateField()),
                ('StartTime', models.TextField()),
                ('EndTime', models.TextField()),
                ('IsActive', models.BooleanField(default=True)),
                ('CreationDate', models.DateField()),
                ('CreationBy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeetingId', models.IntegerField()),
                ('GuestId', models.IntegerField()),
                ('CreationDate', models.DateField()),
                ('CreationBy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingId', models.IntegerField()),
                ('RoomNumber', models.TextField()),
                ('Name', models.CharField(max_length=100)),
                ('Capacity', models.TextField()),
                ('RoomInfo', models.TextField()),
                ('RoomDescription', models.TextField()),
                ('RoomImage', models.ImageField(upload_to='pics')),
                ('IsActive', models.BooleanField(default=True)),
                ('CreationDate', models.DateField()),
                ('CreationBy', models.IntegerField()),
            ],
        ),
    ]
