# Generated by Django 3.0.2 on 2020-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomId', models.IntegerField()),
                ('SeatAvail', models.TextField()),
                ('Area', models.TextField()),
                ('Speed', models.TextField()),
                ('Projector', models.BooleanField(default=True)),
                ('otherEquip', models.TextField()),
            ],
        ),
    ]
